[project]
name = "other-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "natsort>=8.4.0",
    "opencv-python>=4.12.0.88",
]
