[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chumpy>=0.70",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "vedo>=2025.5.4",
]
